logging.level.root=INFO
logging.level.com.admina.api=INFO
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=10
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/user_db
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.flyway.enabled=true
app.notification.enabled=true
app.notification.resend.api-key=${RESEND_API_KEY:}
app.notification.resend.from-email=${RESEND_FROM_EMAIL:}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admina}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admina_password}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false