# ==========================================
# CORE SPRING BOOT
# ==========================================
spring:
  application:
    name: api
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  # ==========================================
  # WEB
  # ==========================================
  web:
    resources:
      add-mappings: false

  # ==========================================
  # FILE UPLOAD
  # ==========================================
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

# ==========================================
# SERVER
# ==========================================
server:
  forward-headers-strategy: framework

# ==========================================
# SECURITY
# ==========================================
app:
  plans:
    limits:
      free:
        max: 2
      standard:
        max: 5
      premium:
        max: 7
  security:
    issuer-uri: ${AZURE_ISSUER_URI}
    audience: ${AZURE_API_AUDIENCE}
    allowed-origins: http://localhost:3000
    public-endpoints:
      - /actuator/info
      - /actuator/health
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v3/api-docs

  # ==========================================
  # RATE LIMITING
  # ==========================================
  ratelimit:
    enabled: true
    requests-per-minute: 60
    window-seconds: 60
    exclude-paths:
      - /actuator/info
      - /actuator/health
      - /swagger-ui.html
      - /v3/api-docs

  # ==========================================
  # DOCUMENT
  # ==========================================
  document:
    max-file-bytes: 6291456
    max-in-flight-documents: 40
    temp-dir: temp
    gemini-api-key: ${GEMINI_API_KEY}

# ==========================================
# OBSERVABILITY & LOGGING
# ==========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

debug: false

springdoc:
  default-produces-media-type: application/json
  
logging:
  level:
    root: INFO
    "[com.admina.api]": INFO
    "[org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver]": OFF
    "[org.springframework.boot.autoconfigure.condition]": OFF
    "[org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger]": OFF
