spring.application.name=api
management.endpoints.web.exposure.include=health,info,metrics
logging.level.root=INFO
logging.level.com.admina.api=INFO
spring.config.import=optional:file:.env[.properties]
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
app.security.audience=${AZURE_API_AUDIENCE}
spring.web.resources.add-mappings=false
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
spring.profiles.active=dev
debug=false
logging.level.org.springframework.boot.autoconfigure.condition=OFF
logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger=OFF
