export const brandStyles = {
  page: "bg-[var(--page-bg)]",
  surface: "bg-[var(--surface)]",
  surfaceMuted: "bg-[var(--surface-muted)]",
  brandBg: "bg-[var(--brand)]",
  brandSoftBg: "bg-[var(--brand-soft)]",
  brandText: "text-[var(--brand)]",
  brandSoftText: "text-[var(--brand-soft)]",
  brandAltText: "text-[var(--brand-alt)]",
  brandDeepText: "text-[var(--brand-deep)]",
  brandBorder: "border-[var(--brand-soft)]",
  brandStrongBorder: "border-[var(--brand)]",
  brandSoftBorder: "border-[var(--brand-soft)]",
  dangerBg: "bg-[var(--danger)]",
  dangerText: "text-[var(--danger)]",
  dangerSoftBg: "bg-[var(--danger-soft)]",
  dangerBorder: "border-[var(--danger)]",
  dangerSoftBorder: "border-[var(--danger-soft)]",
  dangerSoft2Border: "border-[var(--danger-soft-2)]",
  dangerSoft3Border: "border-[var(--danger-soft-3)]",
  dangerLightText: "text-[var(--danger-light)]",
  dangerDarkText: "text-[var(--danger-dark)]",
  successBg: "bg-[var(--success)]",
  successText: "text-[var(--success)]",
  successStrongBg: "bg-[var(--success-strong)]",
  successStrongText: "text-[var(--success-strong)]",
  successStrongBorder: "border-[var(--success-strong)]",
  orangeBg: "bg-[var(--orange)]",
  orangeText: "text-[var(--orange)]",
  orangeSoftBg: "bg-[var(--orange-soft)]",
  warningBg: "bg-[var(--warning)]",
  warningText: "text-[var(--warning)]",
  warningSoftBg: "bg-[var(--warning-soft)]",
  warningSoftBorder: "border-[var(--warning-soft)]",
  mutedText: "text-[var(--muted-text)]",
  neutralText: "text-[var(--neutral-dark)]",
  neutralDarkerText: "text-[var(--neutral-darker)]",
  mutedBorder: "border-[var(--muted-border)]",
  brandAccent: "accent-[var(--brand)]",
  brandButton:
    "bg-[var(--brand)] text-white hover:bg-[var(--brand-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand)] focus-visible:ring-offset-2",
  brandOutlineButton:
    "border-[var(--brand-soft)] text-[var(--brand)] hover:bg-[var(--page-bg)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand)] focus-visible:ring-offset-2",
  dangerOutlineButton:
    "border-[var(--danger)] text-[var(--danger)] hover:bg-[var(--danger-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--danger)] focus-visible:ring-offset-2",
  dangerButton:
    "bg-[var(--danger)] text-white hover:bg-[var(--danger-light)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--danger)] focus-visible:ring-offset-2",
  brandToggle:
    "data-[state=checked]:bg-[var(--brand)] data-[state=unchecked]:bg-[var(--brand-soft)]",
  brandCard: "border-[var(--brand-soft)] bg-[var(--surface)]",
  brandAlert: "border-[var(--brand-soft)] bg-[var(--surface)]",
  pageSection: "bg-[var(--surface)]",
} as const;
